apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-role-binding
subjects:
- kind: ServiceAccount
  name: developer-sa
roleRef:
  kind: ClusterRole
  name: app-editor
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: developer-token
  annotations:
   kubernetes.io/service-account.name: developer-sa
type: kubernetes.io/service-account-token
---
