apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tap-gui-read-k8s
subjects:
- kind: ServiceAccount
  name: developer-sa
roleRef:
  kind: ClusterRole
  name: app-editor
  apiGroup: rbac.authorization.k8s.io
---
